#!/usr/bin/env python3
"""Generate docs/MAP.md — the single traversable index of every doc in the project.

The "wiki front door" ([docs/DOC_SPEC.md](../../docs/DOC_SPEC.md) §5): one page that links every doc
across the platform, the pillars, the modules, the tools and the meta/governance set, so nobody ever
hand-jumps between `docs/`, `src/pillars/`, `src/modules/` and `tools/` again. It is **generated**
from the file tree plus each doc's frontmatter, so it cannot drift: the audit regenerates it in
memory and fails when the committed file differs (`coord map` rewrites it).

**Deterministic by construction.** The output is a pure function of the repo's doc set — no
timestamps, no mtime ordering, no "generated on" line, and POSIX-relative sort keys so Windows and
Linux produce byte-identical bytes. That is what makes `--check` a meaningful gate rather than a
generator of spurious diffs. The map's own `updated` field is the newest `updated` across the docs it
lists, which is itself a pure function of the set.

Usage:
  python3 tools/doc-audit/genmap.py           # rewrite docs/MAP.md
  python3 tools/doc-audit/genmap.py --check    # exit 1 if docs/MAP.md is out of date
  coord map [--check]                          # same, via the developer CLI
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import frontmatter as fm  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent.parent   # tools/doc-audit/ -> repo root
MAP_PATH = REPO_ROOT / "docs" / "MAP.md"
GENERATED_MARKER = (
    "<!-- GENERATED by tools/doc-audit/genmap.py — do not edit by hand; run `coord map` -->"
)

# Directories never descended into. Build outputs and dependency trees are the important ones: a
# restored NuGet cache, a `bin/`/`obj/` tree or a `node_modules/` can contain hundreds of package
# .md files that exist on one machine and not another, which would make MAP.md non-deterministic
# (one machine indexes them, CI does not → "out of date") and its links broken wherever they are
# absent.
SKIP_DIRS = {
    ".git", "__pycache__", ".pytest_cache",
    "node_modules", "dist", "build", "bin", "obj", "out", "publish",
    ".vs", ".vscode", ".idea", "TestResults", "packages",
    ".venv", "venv", "site-packages", "scratchpad", ".artifacts",
}

TIER_ORDER = ["platform", "pillar", "module", "tool", "meta"]
TIER_TITLE = {
    "platform": "Platform — the host itself",
    "pillar": "Pillars — Conduit (input & triggers) · Atlas (desktop truth)",
    "module": "Modules — one self-contained behavior each",
    "tool": "Tools — the developer plane",
    "meta": "Meta — governance, process, capture",
}


def _all_md() -> list[Path]:
    """Every project Markdown file, in a stable order."""
    out: list[Path] = []
    for p in REPO_ROOT.rglob("*.md"):
        # ⚠ Match SKIP_DIRS against the path RELATIVE to the repo root, never against `p.parts`.
        # `p.parts` also tests every ancestor directory ABOVE the checkout, so a clone living under
        # any directory named build/ dist/ out/ venv/ scratchpad/ … would skip *every* file and
        # produce an empty MAP.md plus a confident, false "up to date" verdict. Sandbox and CI
        # working directories land in such paths routinely; the failure is silent and total.
        rel = p.relative_to(REPO_ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        out.append(p)
    # POSIX-relative sort key so the ordering — and therefore the generated bytes — is identical on
    # Windows and on Linux.
    return sorted(out, key=lambda p: p.relative_to(REPO_ROOT).as_posix())


def _infer_tier(rel: str) -> tuple[str, str | None]:
    """`(tier, module)` inferred from a path, for docs that carry no frontmatter.

    Frontmatter always wins; this is the fallback so an un-annotated file still lands somewhere
    sensible instead of vanishing from the index. Mirrors the placement rule in DOC_SPEC §2.1.
    """
    if rel.startswith("docs/decisions/"):
        return "meta", "decisions"
    if rel.startswith("src/modules/"):
        parts = rel.split("/")
        return "module", parts[2] if len(parts) > 3 else None
    if rel.startswith("src/pillars/"):
        parts = rel.split("/")
        return "pillar", parts[2] if len(parts) > 3 else None
    if rel == "docs/CONDUIT.md":
        return "pillar", "conduit"
    if rel == "docs/ATLAS.md":
        return "pillar", "atlas"
    if rel.startswith(("src/platform/", "src/shell/")):
        return "platform", None
    if rel.startswith("tools/"):
        parts = rel.split("/")
        return "tool", parts[1] if len(parts) > 2 else None
    if rel.startswith("tests/"):
        return "tool", "tests"
    if rel.startswith("docs/"):
        return "platform", None
    return "meta", None


def _title_of(path: Path, data: dict | None, body: str) -> str:
    if data and data.get("title"):
        return str(data["title"])
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.name


def _entry(path: Path) -> dict:
    # POSIX (forward slashes) so the generated map is byte-identical across Windows and Linux.
    rel = path.relative_to(REPO_ROOT).as_posix()
    data, body = fm.read(path)
    tier, module = (data.get("tier"), data.get("module")) if data else (None, None)
    if not tier:
        tier, module = _infer_tier(rel)
    if tier not in TIER_ORDER:
        tier = _infer_tier(rel)[0]          # an invalid tier is check_frontmatter's problem, not ours
    return {
        "rel": rel,
        "title": _title_of(path, data, body),
        "tier": tier,
        "module": module,
        "status": (data or {}).get("status"),
        "updated": (data or {}).get("updated"),
    }


def _rellink(from_dir: Path, rel_target: str) -> str:
    target = REPO_ROOT / rel_target
    return os.path.relpath(target, from_dir).replace("\\", "/")


def _fmt_row(e: dict, from_dir: Path) -> str:
    link = _rellink(from_dir, e["rel"])
    meta = [m for m in (e["status"], e["updated"]) if m]
    suffix = f" — {' · '.join(str(m) for m in meta)}" if meta else ""
    return f"- [{e['title']}]({link}) · `{e['rel']}`{suffix}"


def build_map() -> str:
    """The complete text of docs/MAP.md. A pure function of the doc set."""
    entries = [_entry(p) for p in _all_md() if p != MAP_PATH]
    from_dir = MAP_PATH.parent
    updates = sorted(str(e["updated"]) for e in entries if e["updated"])
    map_updated = updates[-1] if updates else "1970-01-01"

    lines: list[str] = []
    # No `audited:` — MAP.md is a generated record, not a living claim about the code (DOC_SPEC §3).
    lines.append(fm.render({
        "title": "Windows Coordinator Documentation Map",
        "tier": "meta",
        "status": "living",
        "updated": map_updated,
        "related": ["docs/DOC_SPEC.md", "docs/AUDIT.md"],
    }).rstrip("\n"))
    lines.append("")
    lines.append(GENERATED_MARKER)
    lines.append("")
    lines.append("# Windows Coordinator Documentation Map")
    lines.append("")
    lines.append("> The single traversable index of every doc in the project — the wiki front door.")
    lines.append("> **Generated** from each doc's frontmatter ([DOC_SPEC.md](DOC_SPEC.md) §5);")
    lines.append("> regenerate with `coord map`. The audit fails when this file is stale, so it")
    lines.append("> cannot drift. Generation is deterministic — a pure function of the doc set, with")
    lines.append("> no timestamps — so `coord map --check` is a real gate rather than a source of")
    lines.append("> noise. The `updated` field above is the newest `updated` across every doc listed.")
    lines.append("")

    # Decisions get their own compact section; everything else groups tier → module.
    adrs = sorted((e for e in entries if e["rel"].startswith("docs/decisions/")),
                  key=lambda e: e["rel"])
    rest = [e for e in entries if not e["rel"].startswith("docs/decisions/")]

    for tier in TIER_ORDER:
        tier_entries = [e for e in rest if e["tier"] == tier]
        if not tier_entries:
            continue
        lines.append(f"## {TIER_TITLE[tier]}")
        lines.append("")
        modules = sorted({str(e["module"]) for e in tier_entries if e["module"]})
        no_module = sorted((e for e in tier_entries if not e["module"]), key=lambda e: e["rel"])
        for e in no_module:
            lines.append(_fmt_row(e, from_dir))
        if no_module:
            lines.append("")
        for mod in modules:
            lines.append(f"### {mod}")
            lines.append("")
            for e in sorted((e for e in tier_entries if str(e["module"]) == mod),
                            key=lambda e: e["rel"]):
                lines.append(_fmt_row(e, from_dir))
            lines.append("")

    if adrs:
        lines.append("## Decisions (ADRs)")
        lines.append("")
        lines.append(f"The unified decision log ({len(adrs)} ADRs) — [docs/decisions/](decisions/). "
                     "Splitting it per module would destroy the two properties that make it useful: "
                     "reading the project's reasoning in the order it happened, and a numbered gap "
                     "being a detectable error.")
        lines.append("")
        for e in adrs:
            lines.append(f"- [{e['title']}]({_rellink(from_dir, e['rel'])})")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


USAGE = """usage: genmap.py [--check]

Regenerate docs/MAP.md, the traversable documentation index (DOC_SPEC §5).

  (no args)   rewrite docs/MAP.md from the current doc set
  --check     exit 1 if the committed docs/MAP.md is out of date; write nothing
  -h, --help  show this message
"""


def main(argv: list[str]) -> int:
    # Validate argv EXPLICITLY rather than substring-testing it. This used to be
    # `check = "--check" in argv`, which made every unrecognised argument mean "rewrite the map" —
    # so a mistyped gate invocation (`--chek`) silently REPAIRED the drift it had been asked to
    # detect and exited 0, and `--help` rewrote the file instead of printing usage. A gate whose
    # failure mode is to erase its own evidence is the sharpest form of "a check that cannot fail"
    # (OPERATING_MODEL §7). Found by an adversarial verifier who tripped it by accident.
    if "-h" in argv or "--help" in argv:
        print(USAGE, end="")
        return 0
    unknown = [a for a in argv if a != "--check"]
    if unknown:
        print(f"genmap.py: unrecognized argument(s): {' '.join(unknown)}\n\n{USAGE}",
              file=sys.stderr)
        return 2
    check = "--check" in argv
    new = build_map()
    if check:
        cur = MAP_PATH.read_text(encoding="utf-8") if MAP_PATH.exists() else ""
        if cur != new:
            what = "is OUT OF DATE" if cur else "does not exist"
            print(f"docs/MAP.md {what} — run `coord map` to regenerate the documentation index.",
                  file=sys.stderr)
            return 1
        print("docs/MAP.md is up to date.")
        return 0
    MAP_PATH.parent.mkdir(parents=True, exist_ok=True)
    MAP_PATH.write_text(new, encoding="utf-8")
    print(f"wrote {MAP_PATH.relative_to(REPO_ROOT).as_posix()} "
          f"({new.count(chr(10))} lines, {len(_all_md()) - 1} docs indexed)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
